party_color_map:
  afd: "#009EE0"      # Blue (AfD)
  spd: "#EB001F"      # Red (SPD)
  gruene: "#64A12D"   # Green (Bündnis 90/Die Grünen)
  linke: "#BE3075"    # Magenta (Die Linke)
  cdu: "#000000"      # Black (CDU)
  fdp: "#FFED00"      # Yellow (FDP)
  unknown: "#404040"  # Grey (Unknown)