party_color_map:
  afd: "#009EE0"      # Blue (AfD)
  spd: "#EB001F"      # Red (SPD)
  die_gruenen: "#64A12D"   # Green (Bündnis 90/Die Grünen)
  die_linke: "#BE3075"    # Magenta (Die Linke)
  cdu_csu: "#000000"      # Black (CDU)
  fdp: "#bfa50f"      # Yellow (FDP)
  unknown: "#404040"  # Grey (Unknown)

platform_color_map:
  Facebook: "#4267B2"
  Instagram: "#E4405F"
  Twitter: "#1DA1F2"